import ativaScroll from "./modulos/scroll-suave.js";
import animacaoAoScroll from "./modulos/animacao-scroll.js";
import initAccordion from "./modulos/accordion.js";
import initTab from "./modulos/tabnav.js";
import initModal from "./modulos/modal.js";
import initTooltip from "./modulos/tooltip.js";
import initDropdownMenu from "./modulos/dropdown-menu.js";
import initMenuMobile from "./modulos/menu-mobile.js";
import initFuncionamento from "./modulos/funcionamento.js";
import initFetchAnimais from "./modulos/fetch-animais.js";

ativaScroll();
animacaoAoScroll();
initAccordion();
initTab();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();